var ChainTypes;

module.exports = ChainTypes = {};

ChainTypes.reserved_spaces = {
  relative_protocol_ids: 0,
  protocol_ids: 1,
  implementation_ids: 2
};

ChainTypes.operations= {
    vote: 0,
    comment: 1,
    transfer: 2,
    // transfer_to_vesting: 3,
    // withdraw_vesting: 4,
    limit_order_create: 3,
    limit_order_cancel: 4,
    // feed_publish: 7,
    // convert: 8,
    account_create: 5,
    account_admin_update: 6,
    account_expertise_update: 7,
    stake_request: 8,
    stake_process: 9,
    account_update: 10,
    witness_update: 11,
    account_witness_vote: 12,
    account_witness_proxy: 13,
    pow: 14,
    custom: 15,
    report_over_production: 16,
    delete_comment: 17,
    custom_json: 18,
    comment_options: 19,
    // set_withdraw_vesting_route: 20,
    limit_order_create2: 20,
    claim_account: 21,
    create_claimed_account: 22,
    request_account_recovery: 23,
    recover_account: 24,
    change_recovery_account: 25,
    escrow_transfer: 26,
    escrow_dispute: 27,
    escrow_release: 28,
    pow2: 29,
    escrow_approve: 30,
    transfer_to_savings: 31,
    transfer_from_savings: 32,
    cancel_transfer_from_savings: 33,
    custom_binary: 34,
    decline_voting_rights: 35,
    reset_account: 36,
    set_reset_account: 37,
    claim_reward_balance: 38,
    // delegate_vesting_shares: 40,
    // account_create_with_delegation: 41,
    witness_set_properties: 39,
    fill_convert_request: 40,
    author_reward: 41,
    curation_reward: 42,
    comment_reward: 43,
    liquidity_reward: 44,
    interest: 45,
    fill_vesting_withdraw: 46,
    fill_order: 47,
    shutdown_witness: 48,
    fill_transfer_from_savings: 49,
    stake_process_time: 50,
    hardfork: 51,
    comment_payout_update: 52,
    return_vesting_delegation: 53,
    comment_benefactor_reward: 54,
    producer_reward: 55,
    clear_null_account_balance: 56,
};

//types.hpp
ChainTypes.object_type = {
  "null": 0,
  base: 1,
};
